# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pradnya', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='team',
            new_name='user',
        ),
    ]
