# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pradnya', '0003_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
