# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pradnya', '0005_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload',
        ),
        migrations.AddField(
            model_name='questions',
            name='time_of_submission',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='total_penalty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='penalty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_penalty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
