# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pradnya', '0006_auto_20160315_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='questiontitle',
            field=models.CharField(blank=True, default='def', max_length=30, null=True),
        ),
    ]
