# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pradnya', '0007_questions_questiontitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
