# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pradnya', '0008_user_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='str_total_time',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
    ]
